# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database chat;' -U postgres

install: true

script: mvn clean package -DskipTests=true

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - qqqiva@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
